# Generated by Django 3.2.10 on 2022-01-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_content_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
