# Generated by Django 3.2.10 on 2022-01-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20220113_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_title', models.CharField(blank=True, max_length=300)),
                ('subreddit', models.CharField(max_length=200)),
                ('strat', models.CharField(max_length=200)),
                ('send_replies', models.BooleanField()),
                ('flair', models.CharField(blank=True, max_length=200)),
                ('reddit_link', models.URLField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strat_type', models.CharField(max_length=200)),
                ('strat_date', models.DateTimeField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.post')),
            ],
        ),
    ]
